# Generated by Django 6.1.1 on 2026-10-01 23:35

import core.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('numero_usuario', models.CharField(db_column='numero_usuario', max_length=30, unique=True, verbose_name='Número de usuario')),
                ('correo_acceso', models.CharField(db_column='correo_acceso', max_length=150, unique=True, verbose_name='Correo de acceso')),
                ('password', models.TextField(db_column='password_hash', verbose_name='Contraseña (hash)')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador del sistema'), ('SECRETARIA', 'Secretaría'), ('MAESTRO', 'Maestro'), ('DIRECTORA', 'Directora'), ('PASTOR_PRINCIPAL', 'Pastor principal'), ('ESTUDIANTE', 'Estudiante')], db_column='rol', max_length=30, verbose_name='Rol')),
                ('estado_cuenta', models.CharField(choices=[('ACTIVA', 'Activa'), ('BLOQUEADA', 'Bloqueada'), ('INACTIVA', 'Inactiva')], db_column='estado_cuenta', default='ACTIVA', max_length=20, verbose_name='Estado de la cuenta')),
                ('debe_cambiar_password', models.BooleanField(db_column='debe_cambiar_password', default=True, verbose_name='¿Debe cambiar contraseña?')),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_acceso', null=True, verbose_name='Último acceso')),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False, verbose_name='¿Es superusuario?')),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False, verbose_name='¿Puede acceder al admin?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion', verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion', verbose_name='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'managed': False,
            },
            managers=[
                ('objects', core.managers.UsuarioManager()),
            ],
        ),
    ]
